version: "3.5"

services:
  vision-api:
    image: vision-api:release
    container_name: vision-api
    restart: always
    build:
      context: .
      dockerfile: VisionAPI/VisionAPI/Dockerfile
    environment:
      - ASPNETCORE_Servers__Domki=http://87.199.89.22/snapshot.jpg
      - ASPNETCORE_Servers__Brama=http://87.199.89.22:81/snapshot.jpg
      - TZ=Europe/Warsaw
      - ASPNETCORE_Cron__DeleteOldVideosCron="0 0 1 * * ?"
    networks:
      - vision-network
    volumes:
      - /mnt/dietpi_userdata/cameras:/app/output
    ports:
      - 9880:80
      - 9444:443
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 150M
  vision-app:
    image: vision-app:release
    container_name: vision-app
    restart: always
    stdin_open: true
    build:
      context: .
      dockerfile: vision/Dockerfile
    environment:
      - TZ=Europe/Warsaw
    ports:
      - 80:80
      - 9004:443
    networks:
      - vision-network
networks:
  vision-network:
    external:
      name: vision-network
