version: "3.5"

services:
  vision-api:
    image: vision-api:release
    restart: always
    build:
      context: .
      dockerfile: VisionAPI/VisionAPI/Dockerfile
    environment:
      - ASPNETCORE_Servers__First=http://87.199.89.22/snapshot.jpg
      - ASPNETCORE_Servers__Second=http://87.199.89.22:81/snapshot.jpg
    networks:
      - vision-network
    ports:
      - 9880:80
      - 9444:443
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 100M
  vision-app:
    image: vision-app:release
    restart: always
    stdin_open: true
    build:
      context: .
      dockerfile: vision/Dockerfile
    ports:
      - 80:80
      - 9004:443
    networks:
      - vision-network
networks:
  vision-network:
    external:
      name: vision-network
